Update capella-ci.yml

diff --git a/.github/workflows/capella-ci.yml b/.github/workflows/capella-ci.yml
--- a/.github/workflows/capella-ci.yml
+++ b/.github/workflows/capella-ci.yml
@@ -23,250 +23,46 @@ env:
 
 jobs:
 
-# ================= BUILD TEST 10.0.0.4================= #
-  BUILD_JOB_TEST_4:
-    runs-on: [self-hosted, TEST_RUNNER_PC]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install NuGet
-      #- name: Setup NuGet
-      #  uses: nuget/setup-nuget@v2
-      - name: Restore NuGet
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |          
-          echo "Nuget restore start"
-          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
-          echo "Nuget restore completed"      
-      
-      - name: Build Solution 
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |
-         echo "Build start"
-         $msbuild = "$env:MSBUILD_PATH"
-         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
-          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
-         
-         & $msbuild $solution `
-         "/p:Configuration=Release" `
-         "/p:DeployOnBuild=true" `
-         "/p:PublishUrl=$publishPath" `
-         "/p:PublishProfile=FolderProfile.pubxml" `
-         "/p:DeleteExistingFiles=true" `
-         "/p:Platform=Any CPU"
-                   
-          echo "Build completed"
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: capella-build
-          path: F:\Acurus_Web\Deployee\builds\Capella_publish
-
-# ================= BUILD TEST 10.0.0.11================= #
-  BUILD_JOB_TEST_11:
-    runs-on: [self-hosted, IIS-2022-Testing-2]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install NuGet
-      #- name: Setup NuGet
-      #  uses: nuget/setup-nuget@v2
-      - name: Restore NuGet
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |          
-          echo "Nuget restore start"
-          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
-          echo "Nuget restore completed"      
-      
-      - name: Build Solution 
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |
-         echo "Build start"
-         $msbuild = "$env:MSBUILD_PATH"
-         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
-          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
-         
-         & $msbuild $solution `
-         "/p:Configuration=Release" `
-         "/p:DeployOnBuild=true" `
-         "/p:PublishUrl=$publishPath" `
-         "/p:PublishProfile=FolderProfile.pubxml" `
-         "/p:DeleteExistingFiles=true" `
-         "/p:Platform=Any CPU"
-                   
-          echo "Build completed"
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: capella-build
-          path: F:\Acurus_Web\Deployee\builds\Capella_publish
-
-# ================= BUILD PRO 10.1.0.6================= #
-  BUILD_JOB_PROD_6:
-    runs-on: [self-hosted, Prod-web-server-1-2022]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install NuGet
-      #- name: Setup NuGet
-      #  uses: nuget/setup-nuget@v2
-      - name: Restore NuGet
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |          
-          echo "Nuget restore start"
-          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
-          echo "Nuget restore completed"      
-      
-      - name: Build Solution 
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |
-         echo "Build start"
-         $msbuild = "$env:MSBUILD_PATH"
-         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
-          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
-         
-         & $msbuild $solution `
-         "/p:Configuration=Release" `
-         "/p:DeployOnBuild=true" `
-         "/p:PublishUrl=$publishPath" `
-         "/p:PublishProfile=FolderProfile.pubxml" `
-         "/p:DeleteExistingFiles=true" `
-         "/p:Platform=Any CPU"
-                   
-          echo "Build completed"
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: capella-build
-          path: F:\Acurus_Web\Deployee\builds\Capella_publish
-
-# ================= BUILD PRO 10.1.0.10================= #
-  BUILD_JOB_PROD_10:
-    runs-on: [self-hosted, Prod-web-server-2-2022]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install NuGet
-      #- name: Setup NuGet
-      #  uses: nuget/setup-nuget@v2
-      - name: Restore NuGet
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |          
-          echo "Nuget restore start"
-          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
-          echo "Nuget restore completed"      
-      
-      - name: Build Solution 
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |
-         echo "Build start"
-         $msbuild = "$env:MSBUILD_PATH"
-         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
-          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
-         
-         & $msbuild $solution `
-         "/p:Configuration=Release" `
-         "/p:DeployOnBuild=true" `
-         "/p:PublishUrl=$publishPath" `
-         "/p:PublishProfile=FolderProfile.pubxml" `
-         "/p:DeleteExistingFiles=true" `
-         "/p:Platform=Any CPU"
-                   
-          echo "Build completed"
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: capella-build
-          path: F:\Acurus_Web\Deployee\builds\Capella_publish
-
-# ================= BUILD PRO 10.1.0.11================= #
-  BUILD_JOB_PROD_11:
-    runs-on: [self-hosted, Prod-web-server]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      # Install NuGet
-      #- name: Setup NuGet
-      #  uses: nuget/setup-nuget@v2
-      - name: Restore NuGet
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |          
-          echo "Nuget restore start"
-          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
-            exit $LASTEXITCODE
-          }
-          echo "Nuget restore completed"      
-      
-      - name: Build Solution 
-        shell: powershell -ExecutionPolicy Bypass {0}
-        run: |
-         echo "Build start"
-         $msbuild = "$env:MSBUILD_PATH"
-         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
-         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
-          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
-         
-         & $msbuild $solution `
-         "/p:Configuration=Release" `
-         "/p:DeployOnBuild=true" `
-         "/p:PublishUrl=$publishPath" `
-         "/p:PublishProfile=FolderProfile.pubxml" `
-         "/p:DeleteExistingFiles=true" `
-         "/p:Platform=Any CPU"
-                   
-          echo "Build completed"
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: capella-build
-          path: F:\Acurus_Web\Deployee\builds\Capella_publish
-
-# ================= DEPLOY TEST 4================= #
+# ================= DEPLOY TEST 4 ================= #
 
   deploy_test_4:
-    needs: build
-    runs-on: [self-hosted, TEST_RUNNER_PC]
+    runs-on: [self-hosted, IIS-2022-Testing-1]
     if: ${{ github.event.inputs.SERVER == '10.0.0.4' }}
 
-    steps:     
-          
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Restore NuGet
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+          echo "Nuget restore start"
+          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
+          echo "Nuget restore completed"
+
+      - name: Build Solution
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+         echo "Build start"
+         $msbuild = "$env:MSBUILD_PATH"
+         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
+          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
+
+         & $msbuild $solution `
+         "/p:Configuration=Release" `
+         "/p:DeployOnBuild=true" `
+         "/p:PublishUrl=$publishPath" `
+         "/p:PublishProfile=FolderProfile.pubxml" `
+         "/p:DeleteExistingFiles=true" `
+         "/p:Platform=Any CPU"
+
+          echo "Build completed"
+
       - name: Deploy to TEST 10.0.0.4
         shell: powershell -ExecutionPolicy Bypass {0}
         run: |
@@ -287,11 +83,11 @@ jobs:
            Write-Error "Source path not found: $sourcePath"
            exit 1
           }
-        
+
           # Create backup folder
           New-Item -ItemType Directory -Path $backupPath -Force
-          
-             echo "Backup CMG MT..Start.."                        
+
+             echo "Backup CMG MT..Start.."
               # Perform Backup
               robocopy "$sourcePath" "$backupPath" /E /COPY:DAT /R:3 /W:5
               if ($LASTEXITCODE -ge 8) {
@@ -313,17 +109,48 @@ jobs:
                 Write-Error "Publish path not found: $publishPath"
                 exit 1
               }
-                                         
+
 
 # ================= DEPLOY TEST 11 ================= #
 
   deploy_test_11:
-    needs: build
     runs-on: [self-hosted, IS-2022-Testing-2]
     if: ${{ github.event.inputs.SERVER == '10.0.0.11' }}
 
-    steps:     
-      
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Restore NuGet
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+          echo "Nuget restore start"
+          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
+          echo "Nuget restore completed"
+
+      - name: Build Solution
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+         echo "Build start"
+         $msbuild = "$env:MSBUILD_PATH"
+         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
+          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
+
+         & $msbuild $solution `
+         "/p:Configuration=Release" `
+         "/p:DeployOnBuild=true" `
+         "/p:PublishUrl=$publishPath" `
+         "/p:PublishProfile=FolderProfile.pubxml" `
+         "/p:DeleteExistingFiles=true" `
+         "/p:Platform=Any CPU"
+
+          echo "Build completed"
+
       - name: Deploy to TEST 10.0.0.11
         shell: powershell -ExecutionPolicy Bypass {0}
         run: |
@@ -371,15 +198,46 @@ jobs:
             exit 1
           }
 
-# ================= DEPLOY PROD 6================= #
+# ================= DEPLOY PROD 6 ================= #
 
   deploy_prod_6:
-    needs: build
     runs-on: [self-hosted, Prod-web-server-1-2022]
     if: ${{ github.event.inputs.SERVER == '10.1.0.6' }}
 
-    steps:     
-          
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Restore NuGet
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+          echo "Nuget restore start"
+          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
+          echo "Nuget restore completed"
+
+      - name: Build Solution
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+         echo "Build start"
+         $msbuild = "$env:MSBUILD_PATH"
+         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
+          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
+
+         & $msbuild $solution `
+         "/p:Configuration=Release" `
+         "/p:DeployOnBuild=true" `
+         "/p:PublishUrl=$publishPath" `
+         "/p:PublishProfile=FolderProfile.pubxml" `
+         "/p:DeleteExistingFiles=true" `
+         "/p:Platform=Any CPU"
+
+          echo "Build completed"
+
       - name: Deploy to PROD 10.1.0.6
         shell: powershell -ExecutionPolicy Bypass {0}
         run: |
@@ -400,10 +258,10 @@ jobs:
            Write-Error "Source path not found: $sourcePath"
            exit 1
           }
-        
+
           # Create backup folder
           New-Item -ItemType Directory -Path $backupPath -Force
-          
+
           echo "Backup CMG ..Start.."
           # Perform Backup
           robocopy "$sourcePath" "$backupPath" /E /COPY:DAT /R:3 /W:5
@@ -426,15 +284,47 @@ jobs:
             Write-Error "Publish path not found: $publishPath"
             exit 1
           }
+
 # ================= DEPLOY PROD 10 ================= #
 
   deploy_prod_10:
-    needs: build
     runs-on: [self-hosted, Prod-web-server-2-2022]
     if: ${{ github.event.inputs.SERVER == '10.1.0.10' }}
 
-    steps:     
-          
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Restore NuGet
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+          echo "Nuget restore start"
+          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
+          echo "Nuget restore completed"
+
+      - name: Build Solution
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+         echo "Build start"
+         $msbuild = "$env:MSBUILD_PATH"
+         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
+          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
+
+         & $msbuild $solution `
+         "/p:Configuration=Release" `
+         "/p:DeployOnBuild=true" `
+         "/p:PublishUrl=$publishPath" `
+         "/p:PublishProfile=FolderProfile.pubxml" `
+         "/p:DeleteExistingFiles=true" `
+         "/p:Platform=Any CPU"
+
+          echo "Build completed"
+
       - name: Deploy to PROD 10.1.0.10
         shell: powershell -ExecutionPolicy Bypass {0}
         run: |
@@ -485,10 +375,43 @@ jobs:
 # ================= DEPLOY PROD 11 ================= #
 
   deploy_prod_11:
-    needs: build
     runs-on: [self-hosted, Prod-web-server]
     if: ${{ github.event.inputs.SERVER == '10.1.0.11' }}
-    steps:     
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Restore NuGet
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+          echo "Nuget restore start"
+          & "$env:NUGET_PATH" restore "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "NuGet restore failed with exit code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
+          echo "Nuget restore completed"
+
+      - name: Build Solution
+        shell: powershell -ExecutionPolicy Bypass {0}
+        run: |
+         echo "Build start"
+         $msbuild = "$env:MSBUILD_PATH"
+         $solution = "$env:GITHUB_WORKSPACE\EHR-Capella5.0.sln"
+         #$publishPath = "$env:GITHUB_WORKSPACE\publish"
+          $publishPath = "F:\Acurus_Web\Deployee\builds\Capella_publish"
+
+         & $msbuild $solution `
+         "/p:Configuration=Release" `
+         "/p:DeployOnBuild=true" `
+         "/p:PublishUrl=$publishPath" `
+         "/p:PublishProfile=FolderProfile.pubxml" `
+         "/p:DeleteExistingFiles=true" `
+         "/p:Platform=Any CPU"
+
+          echo "Build completed"
+
       - name: Deploy to PROD 10.1.0.11
         shell: powershell -ExecutionPolicy Bypass {0}
         run: |
@@ -509,10 +432,10 @@ jobs:
            Write-Error "Source path not found: $sourcePath"
            exit 1
           }
-        
+
           # Create backup folder
           New-Item -ItemType Directory -Path $backupPath -Force
-          
+
           echo "Backup CMG ..Start.."
           # Perform Backup
           robocopy "$sourcePath" "$backupPath" /E /COPY:DAT /R:3 /W:5
